
import type { Translations } from './types';

export const CATEGORIES = ['flutter', 'web', 'android', 'game', 'ios'];

export const TRANSLATIONS: Translations = {
  en: {
    home: 'Home',
    favorites: 'Favorites',
    add: 'Add',
    settings: 'Settings',
    my_prompts: 'My Prompts',
    approve: 'Approve',
    reject: 'Reject',
    copy: 'Copy',
    admin: 'Admin',
    back: 'Back',
    copied: 'Copied!',
    submit: 'Submit',
    generate_with_ai: 'Generate with AI',
    generating: 'Generating...',
    logout: 'Logout',
    language: 'Language',
    user_app: 'User App',
    admin_panel: 'Admin Panel',
    search_prompts: 'Search prompts...',
    all: 'All',
    view: 'View',
    submit_prompt: 'Submit Prompt',
    title: 'Title',
    short_description: 'Short Description',
    category: 'Category',
    icon: 'Icon',
    prompt_text: 'Prompt Text',
    no_favorites: "You haven't favorited any prompts yet.",
    approved_status: 'Approved',
    pending_status: 'Pending',
    no_prompts_submitted: "You haven't submitted any prompts yet.",
    click_add_to_share: "Click the 'Add' button below to share your first prompt!",
    my_prompts_count: 'My Prompts ({count})',
    logged_in_as: 'Logged in as',
    my_profile: 'My Profile',
    view_your_stats: 'View your stats and account info',
    rate_this_idea: 'Rate this Idea',
    your_rating: 'Your rating: {rating}',
    loading_rating: 'Loading your previous rating...',
    edit_profile: 'Edit Profile',
    display_name: 'Display Name',
    save_changes: 'Save Changes',
    saving: 'Saving...',
    welcome_back: 'Welcome Back!',
    create_account: 'Create Account',
    sign_in: 'Sign In',
    sign_up: 'Sign Up',
    processing: 'Processing...',
    or: 'OR',
    sign_in_with_google: 'Sign in with Google',
    need_account: 'Need an account? Sign Up',
    have_account: 'Already have an account? Sign In',
    achievements: 'Achievements',
    refer_a_friend: 'Refer a Friend',
    share_referral: 'Share this link with your friends to invite them to the app!',
    prompts_submitted: 'Prompts Submitted',
    member_since: 'Member since {date}',
    ach_first_steps: 'First Steps',
    ach_first_steps_desc: 'Submit your very first prompt!',
    ach_contributor: 'Contributor',
    ach_contributor_desc: 'Submit 5 prompts.',
    ach_prolific: 'Prolific',
    ach_prolific_desc: 'Submit 10 or more prompts.',
    ach_curator: 'Curator',
    ach_curator_desc: 'Favorite 5 prompts.',
    ach_super_fan: 'Super Fan',
    ach_super_fan_desc: 'Favorite 15 or more prompts.',
    ach_joined: 'Joined!',
    ach_joined_desc: 'Welcome to the community!',
    assistant: 'Assistant',
    ask_anything_dev: 'Ask about app development...',
    thinking: 'Thinking...',
    welcome_assistant: 'Hello! How can I help you with app development today?',
  },
  hi: {
    home: 'होम',
    favorites: 'पसंदीदा',
    add: 'जोड़ें',
    settings: 'सेटिंग्स',
    my_prompts: 'मेरे प्रॉम्प्ट',
    approve: 'मंजूर',
    reject: 'अस्वीकार',
    copy: 'कॉपी',
    admin: 'एडमिन',
    back: 'वापस',
    copied: 'कॉपी किया गया!',
    submit: 'सबमिट करें',
    generate_with_ai: 'एआई से उत्पन्न करें',
    generating: 'उत्पन्न हो रहा है...',
    logout: 'लॉग आउट',
    language: 'भाषा',
    user_app: 'यूज़र ऐप',
    admin_panel: 'एडमिन पैनल',
    search_prompts: 'प्रॉम्प्ट खोजें...',
    all: 'सभी',
    view: 'देखें',
    submit_prompt: 'प्रॉम्प्ट सबमिट करें',
    title: 'शीर्षक',
    short_description: 'संक्षिप्त विवरण',
    category: 'श्रेणी',
    icon: 'आइकन',
    prompt_text: 'प्रॉम्प्ट टेक्स्ट',
    no_favorites: 'आपने अभी तक कोई प्रॉम्प्ट पसंदीदा नहीं किया है।',
    approved_status: 'स्वीकृत',
    pending_status: 'लंबित',
    no_prompts_submitted: 'आपने अभी तक कोई प्रॉMPT सबमिट नहीं किया है।',
    click_add_to_share: "अपना पहला प्रॉम्प्ट साझा करने के लिए नीचे 'जोड़ें' बटन पर क्लिक करें!",
    my_prompts_count: 'मेरे प्रॉम्प्ट ({count})',
    logged_in_as: 'इस रूप में लॉग इन हैं',
    my_profile: 'मेरी प्रोफ़ाइल',
    view_your_stats: 'अपने आँकड़े और खाते की जानकारी देखें',
    rate_this_idea: 'इस आइडिया को रेट करें',
    your_rating: 'आपकी रेटिंग: {rating}',
    loading_rating: 'आपकी पिछली रेटिंग लोड हो रही है...',
    edit_profile: 'प्रोफ़ाइल संपादित करें',
    display_name: 'प्रदर्शित नाम',
    save_changes: 'बदलाव सहेजें',
    saving: 'सहेज रहा है...',
    welcome_back: 'वापसी पर स्वागत है!',
    create_account: 'खाता बनाएं',
    sign_in: 'साइन इन करें',
    sign_up: 'साइन अप करें',
    processing: 'प्रोसेस हो रहा है...',
    or: 'या',
    sign_in_with_google: 'Google से साइन इन करें',
    need_account: 'खाते की आवश्यकता है? साइन अप करें',
    have_account: 'पहले से ही एक खाता है? साइन इन करें',
    achievements: 'उपलब्धियां',
    refer_a_friend: 'एक दोस्त को रेफर करें',
    share_referral: 'इस ऐप में अपने दोस्तों को आमंत्रित करने के लिए यह लिंक साझा करें!',
    prompts_submitted: 'प्रॉम्प्ट सबमिट किए गए',
    member_since: 'सदस्य जबसे {date}',
    ach_first_steps: 'पहला कदम',
    ach_first_steps_desc: 'अपना पहला प्रॉम्प्ट सबमिट करें!',
    ach_contributor: 'योगदानकर्ता',
    ach_contributor_desc: '5 प्रॉम्प्ट सबमिट करें।',
    ach_prolific: 'प्रचुर',
    ach_prolific_desc: '10 या अधिक प्रॉम्प्ट सबमिट करें।',
    ach_curator: 'क्यूरेटर',
    ach_curator_desc: '5 प्रॉम्प्ट पसंदीदा करें।',
    ach_super_fan: 'सुपर फैन',
    ach_super_fan_desc: '15 या अधिक प्रॉम्प्ट पसंदीदा करें।',
    ach_joined: 'शामिल हुए!',
    ach_joined_desc: 'समुदाय में आपका स्वागत है!',
    assistant: 'सहायक',
    ask_anything_dev: 'ऐप डेवलपमेंट के बारे में पूछें...',
    thinking: 'सोच रहा है...',
    welcome_assistant: 'नमस्ते! मैं आज ऐप डेवलपमेंट में आपकी कैसे मदद कर सकता हूँ?',
  }
};

// List of authorized admin User IDs
export const ADMIN_UIDS = ['ZVBsDz8tTdXOLoElAofVwBGeRMj1', 'osjVLYCSdvQaa8jZxYPbY7tracH2'];
